### ISSUE TITLE
Add title filter to checklist

### ISSUE THREAD

**Issue by tadashi-aikawa** [tadashi-aikawa/miroir#30]
## Before

```yaml
  - title: something
    image: '{{ mimizou }}'
    conditions:
```

## After

```yaml
  - title: something
    filter_title: Case[0-9]
    image: '{{ mimizou }}'
    conditions:
```
