### ISSUE TITLE
Disable period in path (Property diffs tab)

### ISSUE THREAD

**Issue by tadashi-aikawa** [tadashi-aikawa/miroir#61]
```
- title: test
  conditions:
    - changed:
      - root<'ab.cd'><'e'>
```

Ignore `{'ab.cd': {'e': 'hoge'}}` on the above case
